name: CI

on:
  push:
    branches:
      - master
    
jobs:
  build:
    name: Build & test with "Node.js v${{ matrix.node-version }}" on "${{ matrix.os }}"  

    strategy:
      fail-fast: false # don't cancel all jobs if some of them failed 
      matrix:
        node-version: [
          # 13,
          # 12,
          11,
          10
        ]
        os: [
          ubuntu-latest,
          # windows-latest,
          macOS-latest
        ]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Test to run the app
        run: npm run start
      - name: Test to run the app with a template
        run: npm run start:ipfs:template
      - name: Start app server
        run: npm run start:app
      - name: Test to run the app with http
        run: npm run start:http
      - name: Test to publish the app
        run: npm run publish:major
      - name: Test to fetch versions published
        run: npm run versions
